(define (squaro x)
  (define (average x y) (/ (+ x y) 2.0))
  (define (average-damp f) (lambda (z) (average z (f z))))
  (define (close-enough? x y)
    (define tolerance 0.00000001)
    (define ratio (/ x y))
    (and (> ratio (- 1 tolerance)) (< ratio (+ 1 tolerance))))
  (define (fixed-point func) 
    (define start 1.0)
    (define (iter start end)
      (if (close-enough? start end) end (iter end (func end))))
    (iter start (func start)))
  (fixed-point(average-damp(lambda (y) (/ x y)))))