/*
 * MainForm.java
 *
 * Created on April 20, 2007, 8:27 PM
 */

package equationprogram;

import javax.swing.*;

/**
 * The old GUI of the application.
 * @author Sami Safadi
 */
public class MainForm extends javax.swing.JFrame {
    private QuadricEq e1;
    private QuadricEqPlot p1;
    private JFrame f;
    
    /** Creates new form MainForm */
    public MainForm() {              
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel_Info = new javax.swing.JLabel();
        jPanel_Input = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Text_a = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Text_b = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Text_c = new javax.swing.JTextField();
        jButton_Solve = new javax.swing.JButton();
        jButton_About = new javax.swing.JButton();
        jPanel_Output = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        LabelEqType = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LabelRoot1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LabelRoot2 = new javax.swing.JLabel();
        jPanel_Plot = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jText_x1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jText_x2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jText_y1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jText_y2 = new javax.swing.JTextField();
        jButton_Draw = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("\u0628\u0631\u0646\u0627\u0645\u062c \u062d\u0644 \u0627\u0644\u0645\u0639\u0627\u062f\u0644\u0627\u062a \u0627\u0644\u0634\u0647\u064a\u0631 \u0645\u0646 \u0633\u0627\u0645\u064a \u0635\u0641\u062f\u064a");
        setResizable(false);
        jLabel_Info.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel_Info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Info.setText("\u0627\u0644\u0645\u0639\u0627\u062f\u0644\u0629 \u0645\u0646 \u0627\u0644\u062f\u0631\u062c\u0629 \u0627\u0644\u062b\u0627\u0646\u064a\u0629 \u0648\u0644\u0647\u0627 \u0627\u0644\u0634\u0643\u0644 \u0623 \u06332 + \u0628 \u0633 + \u062c = 0");

        jPanel_Input.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "\u0645\u0639\u0637\u064a\u0627\u062a \u0627\u0644\u0645\u0639\u0627\u062f\u0644\u0629", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel_Input.setToolTipText("\u0625\u062f\u062e\u0627\u0644 \u0645\u062a\u063a\u064a\u0631\u0627\u062a \u0627\u0644\u0645\u0639\u0627\u062f\u0644\u0629");
        jPanel_Input.setMaximumSize(new java.awt.Dimension(500, 200));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("\u0623\u062f\u062e\u0644 \u0642\u064a\u0645\u0629 \u0623");

        Text_a.setNextFocusableComponent(Text_b);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("\u0623\u062f\u062e\u0644 \u0642\u064a\u0645\u0629 \u0628");

        Text_b.setNextFocusableComponent(Text_c);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("\u0623\u062f\u062e\u0644 \u0642\u064a\u0645\u0629 \u062c");

        Text_c.setNextFocusableComponent(jButton_Solve);

        org.jdesktop.layout.GroupLayout jPanel_InputLayout = new org.jdesktop.layout.GroupLayout(jPanel_Input);
        jPanel_Input.setLayout(jPanel_InputLayout);
        jPanel_InputLayout.setHorizontalGroup(
            jPanel_InputLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel_InputLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel_InputLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel_InputLayout.createSequentialGroup()
                        .add(Text_a, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 277, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(40, 40, 40))
                    .add(jPanel_InputLayout.createSequentialGroup()
                        .add(jPanel_InputLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel_InputLayout.createSequentialGroup()
                                .add(Text_b, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 277, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(40, 40, 40))
                            .add(jPanel_InputLayout.createSequentialGroup()
                                .add(Text_c, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 277, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(40, 40, 40)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                .add(jPanel_InputLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel1)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel2)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel3, 0, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_InputLayout.setVerticalGroup(
            jPanel_InputLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel_InputLayout.createSequentialGroup()
                .add(jPanel_InputLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Text_a, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel_InputLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Text_b, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel_InputLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Text_c, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jButton_Solve.setText("\u062d\u0644 \u0627\u0644\u0645\u0639\u0627\u062f\u0644\u0629");
        jButton_Solve.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Solve.setNextFocusableComponent(jText_x1);
        jButton_Solve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolveEquation(evt);
            }
        });

        jButton_About.setText("\u0639\u0646 \u0627\u0644\u0645\u0624\u0644\u0641");
        jButton_About.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_About.setNextFocusableComponent(Text_a);
        jButton_About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutAuthor(evt);
            }
        });

        jPanel_Output.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "\u062d\u0644 \u0627\u0644\u0645\u0639\u0627\u062f\u0644\u0629", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel_Output.setToolTipText("\u062d\u0644 \u0627\u0644\u0645\u0639\u0627\u062f\u0644\u0629 \u0627\u0639\u062a\u0645\u0627\u062f\u0627 \u0639\u0644\u0649 \u0627\u0644\u0645\u0639\u0637\u064a\u0627\u062a \u0627\u0644\u0645\u062f\u062e\u0644\u0629");
        jPanel_Output.setMaximumSize(new java.awt.Dimension(500, 200));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("\u0646\u0648\u0639 \u0627\u0644\u0645\u0639\u0627\u062f\u0644\u0629");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("\u0627\u0644\u062c\u0630\u0631 \u0627\u0644\u0623\u0648\u0644");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("\u0627\u0644\u062c\u0630\u0631 \u0627\u0644\u062b\u0627\u0646\u064a");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        org.jdesktop.layout.GroupLayout jPanel_OutputLayout = new org.jdesktop.layout.GroupLayout(jPanel_Output);
        jPanel_Output.setLayout(jPanel_OutputLayout);
        jPanel_OutputLayout.setHorizontalGroup(
            jPanel_OutputLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel_OutputLayout.createSequentialGroup()
                .add(26, 26, 26)
                .add(jPanel_OutputLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(LabelRoot2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 270, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(LabelEqType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 270, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(LabelRoot1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 270, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 27, Short.MAX_VALUE)
                .add(jPanel_OutputLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel_OutputLayout.createSequentialGroup()
                        .add(1, 1, 1)
                        .add(jLabel6))
                    .add(jPanel_OutputLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(jLabel7)
                        .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel_OutputLayout.linkSize(new java.awt.Component[] {LabelEqType, LabelRoot1, LabelRoot2}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel_OutputLayout.setVerticalGroup(
            jPanel_OutputLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel_OutputLayout.createSequentialGroup()
                .add(jPanel_OutputLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel_OutputLayout.createSequentialGroup()
                        .add(LabelEqType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(LabelRoot1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(LabelRoot2))
                    .add(jPanel_OutputLayout.createSequentialGroup()
                        .add(jLabel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel6)))
                .addContainerGap())
        );

        jPanel_OutputLayout.linkSize(new java.awt.Component[] {LabelEqType, LabelRoot1, LabelRoot2}, org.jdesktop.layout.GroupLayout.VERTICAL);

        jPanel_Plot.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "\u0631\u0633\u0645 \u0627\u0644\u062e\u0637 \u0627\u0644\u0628\u064a\u0627\u0646\u064a \u0644\u0644\u062a\u0627\u0628\u0639 \u0627\u0644\u0645\u0648\u0627\u0641\u0642", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jLabel8.setText("\u0639\u0644\u0649 \u0627\u0644\u0645\u062d\u0648\u0631 x \u0645\u0646");

        jText_x1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText_x1.setText("-100");
        jText_x1.setNextFocusableComponent(jText_x2);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("\u0625\u0644\u0649");

        jText_x2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText_x2.setText("100");
        jText_x2.setNextFocusableComponent(jText_y1);

        jLabel9.setText("\u0639\u0644\u0649 \u0627\u0644\u0645\u062d\u0648\u0631 y \u0645\u0646");

        jText_y1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText_y1.setText("-100");
        jText_y1.setNextFocusableComponent(jText_y2);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("\u0625\u0644\u0649");

        jText_y2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jText_y2.setText("100");
        jText_y2.setNextFocusableComponent(jButton_Draw);

        jButton_Draw.setText("\u0631\u0633\u0645");
        jButton_Draw.setActionCommand("\u0631\u0633\u0645 \u0627\u0644\u062e\u0637 \u0627\u0644\u0628\u064a\u0627\u0646\u064a");
        jButton_Draw.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Draw.setNextFocusableComponent(jButton_About);
        jButton_Draw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlotFunction(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel_PlotLayout = new org.jdesktop.layout.GroupLayout(jPanel_Plot);
        jPanel_Plot.setLayout(jPanel_PlotLayout);
        jPanel_PlotLayout.setHorizontalGroup(
            jPanel_PlotLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel_PlotLayout.createSequentialGroup()
                .add(0, 10, Short.MAX_VALUE)
                .add(jButton_Draw)
                .add(16, 16, 16)
                .add(jPanel_PlotLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel_PlotLayout.createSequentialGroup()
                        .add(jText_x2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jText_x1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel8))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel_PlotLayout.createSequentialGroup()
                        .add(jText_y2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jText_y1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel9)))
                .add(10, 10, 10))
        );

        jPanel_PlotLayout.linkSize(new java.awt.Component[] {jText_x1, jText_x2, jText_y1, jText_y2}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel_PlotLayout.setVerticalGroup(
            jPanel_PlotLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel_PlotLayout.createSequentialGroup()
                .add(jPanel_PlotLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel_PlotLayout.createSequentialGroup()
                        .add(jPanel_PlotLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jText_x2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel8)
                            .add(jText_x1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel10))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel_PlotLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jText_y2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel9)
                            .add(jText_y1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel11)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jButton_Draw, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel_PlotLayout.linkSize(new java.awt.Component[] {jText_x1, jText_x2, jText_y1, jText_y2}, org.jdesktop.layout.GroupLayout.VERTICAL);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel_Info, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel_Plot, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jButton_Solve, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 97, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jButton_About, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 97, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel_Input, 0, 403, Short.MAX_VALUE)
                    .add(jPanel_Output, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {jButton_About, jButton_Solve}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel_Info, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel_Input, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton_Solve, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton_About, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel_Plot, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel_Output, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {jButton_About, jButton_Solve}, org.jdesktop.layout.GroupLayout.VERTICAL);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlotFunction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlotFunction
        double x1,x2,y1,y2;
        x1 = Double.parseDouble(jText_x1.getText());
        x2 = Double.parseDouble(jText_x2.getText());
        y1 = Double.parseDouble(jText_y1.getText());
        y2 = Double.parseDouble(jText_y2.getText());
        
        //Create a new plot object
        QuadricEqPlot p1= new QuadricEqPlot(e1,x1,x2,y1,y2);
        
        //Create a new plot frame, and add the plot object to it
        f= new JFrame("Plotting the equation: " + e1 );
        f.setSize(p1.getWidth(),p1.getHeight());
        f.getContentPane().add(p1);
        f.setLocation(100,100);
        f.setVisible(true);
    }//GEN-LAST:event_PlotFunction

    private void AboutAuthor(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutAuthor
        JOptionPane.showMessageDialog(null,"Sami Safadi, a world leading figure in mathematical equation software");
    }//GEN-LAST:event_AboutAuthor

    private void SolveEquation(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolveEquation
        double a,b,c;

        a = Double.parseDouble(Text_a.getText());
        b = Double.parseDouble(Text_b.getText());
        c = Double.parseDouble(Text_c.getText());
                   
        //creates an equation and solve it
        e1 = new QuadricEq(a,b,c);

        //display the roots
        LabelRoot1.setText(e1.getRoot1());
        LabelRoot2.setText(e1.getRoot2());
        LabelEqType.setText(e1.getType());

        
    }//GEN-LAST:event_SolveEquation
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelEqType;
    private javax.swing.JLabel LabelRoot1;
    private javax.swing.JLabel LabelRoot2;
    private javax.swing.JTextField Text_a;
    private javax.swing.JTextField Text_b;
    private javax.swing.JTextField Text_c;
    private javax.swing.JButton jButton_About;
    private javax.swing.JButton jButton_Draw;
    private javax.swing.JButton jButton_Solve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Info;
    private javax.swing.JPanel jPanel_Input;
    private javax.swing.JPanel jPanel_Output;
    private javax.swing.JPanel jPanel_Plot;
    private javax.swing.JTextField jText_x1;
    private javax.swing.JTextField jText_x2;
    private javax.swing.JTextField jText_y1;
    private javax.swing.JTextField jText_y2;
    // End of variables declaration//GEN-END:variables
    
}
